# Generated by Django 2.2.8 on 2019-12-17 03:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20191217_0850'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MovieLinks',
            new_name='MovieLink',
        ),
    ]
