# Generated by Django 2.2.8 on 2019-12-17 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0003_auto_20191217_0854'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movielink',
            old_name='type',
            new_name='link_type',
        ),
    ]
