# Generated by Django 2.2.8 on 2019-12-17 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_auto_20191217_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielink',
            name='movie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_link', to='movie.Movie'),
        ),
    ]
