# Generated by Django 2.2.8 on 2019-12-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_auto_20191217_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movielink',
            name='link_type',
            field=models.CharField(choices=[('W', 'WATCH LINK'), ('D', 'DOWNLOAD LINK'), ('T', 'TRAILER LINK')], max_length=1),
        ),
    ]
