# Generated by Django 2.2.8 on 2019-12-17 12:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0007_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 17, 12, 7, 51, 756658, tzinfo=utc)),
        ),
    ]
