# Generated by Django 2.2.8 on 2019-12-18 04:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0008_movie_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='banner',
            field=models.ImageField(default='', upload_to='movie banners'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 12, 18, 4, 55, 4, 404490, tzinfo=utc)),
        ),
    ]
